### ISSUE TITLE
Wrong patterns

### ISSUE THREAD

**Issue by jartaud** [merlos/cedula-panama#1]
Panameño nacido en el extranjero (PE is legacy):
http://www.tribunal-electoral.gob.pa/aclaracion-inscripciones-panamenos-nacidos-exterior/

Extranjero con cédula (E/N-libro-tomo is legacy): E-Provincia-Tomo is the new pattern.

With your actual logic a "E/N" cedula like: E-8-111111 would be invalid. So you'll have to support legacy and new pattern.

**Comment by merlos** [comment]
Hola @jartaud 

Muchas gracias por tu comentario.

E-8-123456 es un formato que el validador daría como correcto. El patrón que se asume como correctos es: Letra E seguida de un guión. Luego de 1 a 4 números, un guión, de 1 a 6 números. 

Según lo que tú comentas, en caso de que la E fuera seguida número igual o menor a 13, por ejemplo E-8-123, el número corresponde a una provincia y no a un libro (patrón nuevo).  Es decir, asumimos que no hay libros con número menor de 13.

Sin embargo, E-123-1234 sería un extranjero con cédula (legacy) y el 123 sería un libro. 

Es correcto?

Muchas gracias.
Saludos, Juan.

**Comment by jartaud** [comment]
isValid is false.

![Ves?](https://i.imgur.com/WqrFkFQ.png)

**Comment by ecedenyo** [comment]
isValid es false porque en el último grupo de números se están ingresando 6 dígitos, cuando el formato está aceptando hasta 5 dígitos, soy extranjero con cédula E, he introducido mi cédula y la está validando correctamente bajo el formato: E-9-**99999**

**Comment by merlos** [comment]
Gracias @ecedenyo. Tienes razón, hasta lo que yo encontré el último grupo de números, el asiento, solo soporta 5 números. 

@jartaud, Cierro el issue. Si tienes algún comentario, siéntete libre de reabrirlo.

**Comment by jartaud** [comment]
Yo también soy extranjero y mi cédula tiene 6 dígitos: E-8-999999. No hay un regla que dice que tiene que tener 5 dígitos. Quizá ustedes sacaron la cédula hace tiempo. La mía tiene 5 años y es de 6 dígitos después de la provincia.
