### ISSUE TITLE
El patron no funciona en input de html

### ISSUE THREAD

**Issue by AlexisSniffer** [merlos/cedula-panama#6]
Al poner 8- lo valida como cierto.

`<input class="input" type="text" placeholder=""
pattern="/^P$|^(?:PE|E|N|[23456789]|[23456789](?:A|P)?|1[0123]?|1[0123]?(?:A|P)?)$|^(?:PE|E|N|[23456789]|[23456789](?:AV|PI)?|1[0123]?|1[0123]?(?:AV|PI)?)-?$|^(?:PE|E|N|[23456789](?:AV|PI)?|1[0123]?(?:AV|PI)?)-(?:\d{1,4})-?$|^(PE|E|N|[23456789](?:AV|PI)?|1[0123]?(?:AV|PI)?)-(\d{1,4})-(\d{1,6})$/i" required>`

**Comment by merlos** [comment]
La expresión regular completa te indica si hasta el momento, lo que ha escrito el usuario hasta el momento sigue el patrón de una cédula. 

Si quieres saber si lo que está dentro del campo es una cédula completa tienes que usar solo la última porción del patrón  `^(PE|E|N|[23456789](?:AV|PI)?|1[0123]?(?:AV|PI)?)-(\d{1,4})-(\d{1,6})$/i"`
